service: productsService
frameworkVersion: '3'
useDotenv: true

custom:
    esbuild:
        bundle: true
        minify: false
        sourcemap: true
        exclude: ['aws-sdk']
        target: node14
        platform: node
        concurrency: 10
    MAIN_REGION: eu-central-1
    QUEUE_NAME: CatalogItemsQueue
    SQS_QUEUE_URL: { Ref: CatalogItemsQueue }
    SNS_TOPIC_NAME: createProductTopic

provider:
    name: aws
    runtime: nodejs14.x
    region: ${self:custom.MAIN_REGION}
    environment:
        REGION: ${self:custom.MAIN_REGION}
        QUEUE_URL: ${self:custom.SQS_QUEUE_URL}
        CREATE_PRODUCT_TOPIC_ARN: !Ref CreateProductTopic
        MYSQL_DB_HOST: ${env:MYSQL_DB_HOST}
        MYSQL_DB_USER: ${env:MYSQL_DB_USER}
        MYSQL_DB_PASSWORD: ${env:MYSQL_DB_PASSWORD}

    iamRoleStatements:
        - Effect: Allow
          Action:
              - sqs:*
          Resource:
              Fn::GetAtt: [CatalogItemsQueue, Arn]
        - Effect: Allow
          Action:
              - sns:*
          Resource: !Ref CreateProductTopic

resources:
    Resources:
        CatalogItemsQueue:
            Type: AWS::SQS::Queue
            Properties:
                QueueName: sqs-${self:custom.QUEUE_NAME}-${sls:stage}.fifo
                FifoQueue: true
        CreateProductTopic:
            Type: AWS::SNS::Topic
            Properties:
                TopicName: ${self:custom.SNS_TOPIC_NAME}
        EmailSend:
            Type: AWS::SNS::Subscription
            Properties:
                Endpoint: ${env:EMAIL}
                Protocol: email
                TopicArn: !Ref CreateProductTopic
        EmailSendWithFilter:
            Type: AWS::SNS::Subscription
            Properties:
                Endpoint: ${env:FILTER_EMAIL}
                Protocol: email
                TopicArn: !Ref CreateProductTopic
                FilterPolicyScope: MessageAttributes
                FilterPolicy: { 'isBYDLoaded': ['yes'] }

functions:
    - ${file('src/functions/getProductById/index.yml')}
    - ${file('src/functions/getProductList/index.yml')}
    - ${file('src/functions/createProduct/index.yml')}
    - ${file('src/functions/catalogBatchProcess/index.yml')}

plugins:
    - serverless-esbuild
