service: productsService
frameworkVersion: '3'

custom:
    esbuild:
        bundle: true
        minify: false
        sourcemap: true
        exclude: ['aws-sdk']
        target: node14
        platform: node
        concurrency: 10
    MAIN_REGION: eu-central-1
    QUEUE_NAME: CatalogItemsQueue
    SQS_QUEUE_URL: { Ref: CatalogItemsQueue }

provider:
    name: aws
    runtime: nodejs14.x
    region: ${self:custom.MAIN_REGION}
    environment:
        REGION: ${self:custom.MAIN_REGION}

    iamRoleStatements:
        - Effect: Allow
          Action:
              - sqs:*
          Resource:
              Fn::GetAtt: [CatalogItemsQueue, Arn]

resources:
    Resources:
        CatalogItemsQueue:
            Type: 'AWS::SQS::Queue'
            Properties:
                QueueName: sqs-${self:custom.QUEUE_NAME}-${sls:stage}.fifo
                FifoQueue: true

functions:
    - ${file('src/functions/getProductById/index.yml')}
    - ${file('src/functions/getProductList/index.yml')}
    - ${file('src/functions/createProduct/index.yml')}
    - ${file('src/functions/catalogBatchProcess/index.yml')}

plugins:
    - serverless-dotenv-plugin
    - serverless-esbuild
