service: importService
frameworkVersion: '3'

custom:
    esbuild:
        bundle: true
        minify: false
        sourcemap: true
        exclude: ['aws-sdk']
        target: node14
        platform: node
        concurrency: 10
    UPLOAD_BUCKET: shushmanshop-static
    QUEUE_NAME: sqs-CatalogItemsQueue-${sls:stage}.fifo
    QUEUE_URL: https://sqs.${aws:region}.amazonaws.com/${aws:accountId}/${self:custom.QUEUE_NAME}
    BASIC_AUTHORIZER_ARN: arn:aws:lambda:${aws:region}:${aws:accountId}:function:authService-${sls:stage}-basicAuthorizer

provider:
    name: aws
    runtime: nodejs14.x
    region: ${opt:region, 'eu-central-1'}
    environment:
        REGION: ${aws:region}
        UPLOAD_BUCKET: ${self:custom.UPLOAD_BUCKET}
        QUEUE_URL: ${self:custom.QUEUE_URL}

    httpApi:
        cors: true
        authorizers:
            basicAuthorizer:
                type: request
                functionArn: ${self:custom.BASIC_AUTHORIZER_ARN}
                resultTtlInSeconds: 0
                identitySource:
                    - $request.header.Authorization

    iamRoleStatements:
        - Effect: 'Allow'
          Action: 's3:ListBucket'
          Resource:
              - 'arn:aws:s3:::shushmanshop-static'
        - Effect: 'Allow'
          Action:
              - 's3:*'
          Resource:
              - 'arn:aws:s3:::shushmanshop-static/*'
        - Effect: 'Allow'
          Action:
              - 'sqs:*'
          Resource:
              - 'arn:aws:sqs:${aws:region}:${aws:accountId}:${self:custom.QUEUE_NAME}'

functions:
    importProductsFile:
        handler: src/functions/importProductsFile/handler.main
        events:
            - httpApi:
                  path: /import
                  method: get
                  authorizer:
                      name: basicAuthorizer

    importFileParser:
        handler: src/functions/importFileParser/handler.importFileParser
        events:
            - s3:
                  bucket: ${self:custom.UPLOAD_BUCKET}
                  event: s3:ObjectCreated:*
                  rules:
                      - prefix: uploaded/
                      - suffix: .csv
                  existing: true
                  forceDeploy: true

plugins:
    - serverless-esbuild
