service: importService
frameworkVersion: '3'

custom:
    esbuild:
        bundle: true
        minify: false
        sourcemap: true
        exclude: ['aws-sdk']
        target: node14
        platform: node
        concurrency: 10
    MAIN_REGION: eu-central-1
    UPLOAD_BUCKET: shushmanshop-static

provider:
    name: aws
    runtime: nodejs14.x
    region: ${self:custom.MAIN_REGION}
    environment:
        REGION: ${self:custom.MAIN_REGION}
        UPLOAD_BUCKET: ${self:custom.UPLOAD_BUCKET}

functions:
    importProductsFile:
        handler: src/functions/importProductsFile/handler.main
        events:
            - httpApi:
                  path: /import
                  method: get

plugins:
    - serverless-dotenv-plugin
    - serverless-esbuild
